import { usePreferences } from "@/app/preferences";
const zh = {
  noteList: "笔记列表", selectNotes: "多选笔记", selectNote: "选择笔记", cancelSelection: "取消多选", selectVisible: "全选当前列表", selectedCount: (count:number)=>`已选 ${count} 篇`, noneSelected: "还没有勾选笔记", batchActions: "批量操作",
  openNote: "打开笔记", rename: "重命名", duplicate: "创建副本", unfavorite: "取消收藏", copySuffix: "副本", partialFailure: (count:number)=>`${count} 篇笔记操作失败，请重试。`,
  referenceVersion: (version:number)=>`引用自版本 ${version}，当前显示最新正文`, viewReference: "查看引用版本",

  actions: "笔记操作", close: "关闭属性",
  insert: "插入",
  deleteForever: "彻底删除", deleteWarning: "笔记及所有历史版本将被永久删除，无法恢复。已有引用会保留，但无法再打开来源。", inTrash: "这篇笔记已移入回收站。恢复后可以继续编辑。",
  bold: "粗体", italic: "斜体", strike: "删除线", heading: "段落样式", paragraph: "正文", headingLevels: ["一级标题", "二级标题", "三级标题", "四级标题", "五级标题", "六级标题"], bulletList: "无序列表", numberedList: "有序列表", taskList: "任务列表", quote: "引用块", code: "代码块", divider: "分隔线", image: "插入图片", imageHint: "也可粘贴或拖入", uploading: "图片上传中…", undo: "撤销", redo: "重做", nothingToUndo: "没有可撤销的操作", nothingToRedo: "没有可重做的操作", link: "网页链接", apply: "应用", table: "表格", insertTable: "插入表格", tableSize: (rows:number, cols:number)=>`${rows} × ${cols}`, addRow: "在下方插入行", addColumn: "在右侧插入列", deleteRow: "删除当前行", deleteColumn: "删除当前列", deleteTable: "删除表格",
  listEmpty: "还没有笔记", listEmptyHint: "写下第一个想法，慢慢积累你的创作资料。", trashEmpty: "回收站是空的", trashHint: "移入回收站的笔记可以在这里恢复。", favoriteEmpty: "还没有收藏", favoriteHint: "给常用笔记点亮星标，下次更容易找到。", searchHint: "换个关键词，或清除筛选再看看。", clearSearch: "清除筛选",
  title: "笔记", all: "全部笔记", favorite: "收藏", trash: "回收站", topics: "专题", tags: "标签",
  new: "新建笔记", search: "搜索标题、正文或标签", untitled: "未命名笔记", empty: "把值得留下的想法写在这里",
  emptyHint: "记录灵感，也可以从逐字稿、对话和画板中保存摘录。", noResults: "没有找到笔记",
  saved: "已保存", saving: "保存中…", draft: "草稿待保存", error: "保存失败，草稿已留在本机", retry: "重试保存",
  conflict: "笔记已有新版本。本机草稿已保留，请先导出草稿再载入最新版本。", reload: "载入最新版本",
  source: "来源与属性", history: "版本记录", restore: "恢复此版本", restoreTrash: "移出回收站", moveTrash: "移入回收站",
  import: "导入 Markdown", dropHint: "松开导入为笔记(.md / .markdown / .txt)", importUnsupported: "只能导入 .md、.markdown 或 .txt 文件", imported: (n:number)=>`已导入 ${n} 篇笔记`, importPartial: (n:number, failed:string[])=>`已导入 ${n} 篇,${failed.length} 个没导入(超过 500 KB 或读取失败):${failed.slice(0,3).join("、")}${failed.length>3?"…":""}`, export: "导出 Markdown", format: "格式工具", moreFormats: "更多格式", versionContent: "版本内容", raw: "Markdown", rawHint: "看 Markdown 源码,再点一下回到编辑",
  content: "笔记正文", placeholder: "开始写作，或输入 @ 引用另一篇笔记…", addReference: "引用笔记",
  topicHint: "专题，用逗号分隔", tagHint: "标签，用逗号分隔", sourcesEmpty: "从素材或对话保存摘录后，可在这里回到来源。",
  saveTo: "保存到笔记", nothingToSave: "还没有可保存的内容", append: "追加到已有笔记", choose: "选择笔记", excerpt: "摘录", done: "已保存到笔记",
  shape: "正文形状", shapePlain: "正文", shapeCited: "带时间戳引用",
  saveAsNew: "存为新笔记", noteTitle: "笔记标题", create: "新建", titleHint: "留空时取正文开头作为标题。",
  willSave: (chars:number, sources:number)=>`将写入约 ${chars} 字，附 ${sources} 条来源`,
  saveAll: "全部存为笔记", saveAllTranscript: "把整份逐字稿存成一篇笔记。选中了片段就只存选中的那些。",
  saveAllSubtitles: "把整条字幕轨存成一篇笔记；有译文时原文与译文一起写入。",
  localDraft: "已恢复本机未保存草稿", more: "加载更多",
  askAi: "问 AI", askAiHint: "带着选中的文字问助手", passageGone: "那段文字已经改过了,没在笔记里找到。", focus: "专注写作", exitFocus: "显示列表", unavailable: "来源已删除或无法访问", loading: "正在载入…",
  selection: {
    toolbar: "选区工具", inlineCode: "行内代码", highlight: "高亮", unlink: "去掉链接", linkPlaceholder: "粘贴 https:// 链接后回车",
    ai: "AI 动作", more: "更多", copy: "复制", copied: "已复制", quote: "引用到对话", addToBoard: "加到画板",
    readAloud: "朗读", stopReading: "停止朗读", readingWithVoice: "正在用你在「语音对话」里选的音色朗读", readingWithEdge: "正在用免费的 Edge 语音朗读", saveAudio: "存为音频素材", savingAudio: "已开始生成音频,完成后在素材库里",
    actions: {
      polish: { label: "润色", hint: "让表达更通顺、更得体,意思不变", prompt: "润色选中的这段" },
      rewrite: { label: "改写", hint: "换一种说法重写这段,意思不变", prompt: "改写选中的这段" },
      expand: { label: "扩写", hint: "补充细节和例子,写得更充分", prompt: "扩写选中的这段" },
      shorten: { label: "缩写", hint: "只留要点,写得更短", prompt: "缩写选中的这段" },
      translate: { label: "翻译", hint: "中文译成英文,其他语言译成中文", prompt: "把选中的这段翻译成{lang}" },
      summarize: { label: "总结", hint: "在对话里总结要点,不改笔记", prompt: "总结选中的这段" },
      explain: { label: "解释", hint: "在对话里解释这段在说什么,不改笔记", prompt: "解释选中的这段" },
      continue: { label: "续写", hint: "接着这段往下写一段,插在它后面", prompt: "接着选中的这段往下写" },
    },
    languages: { en: "英文", zh: "中文" },
  },
  board: {
    title: "加到画板", search: "搜索画板", empty: "还没有画板", noMatch: "没有叫这个的画板", loading: "正在载入画板…",
    newBoard: "新建画板", newBoardNamed: (name: string) => `新建画板「${name}」`, defaultName: "新画板",
    added: (name: string) => `已加到画板「${name}」`, open: "打开画板",
  },
  node: {
    imageLink: "图片链接",
    alt: "替代文字",
    apply: "应用图片修改",
    cancel: "取消图片修改",
    invalid: "请输入 https:// 图片地址或已有的素材引用。",
    unavailable: "图片无法显示",
    preview: "看大图",
    previewOf: (n: number) => `笔记图片 ${n}`,
    language: "代码语言",
    plain: "纯文本",
    copy: "复制代码",
    copied: "已复制",
    failed: "复制失败，请选中代码手动复制。",
  },
  //: 版本记录弹窗(NoteHistoryDialog)。
  versions: {
    hint: "恢复会新建一个版本，现有版本都还在。",
    list: "版本列表",
    current: "当前版本",
    version: (n: number) => `版本 ${n}`,
    today: "今天",
    yesterday: "昨天",
    copy: "复制这一版的内容",
    copied: (n: number) => `已复制版本 ${n} 的正文`,
    restore: "恢复此版本",
    restoreTitle: (n: number) => `恢复到版本 ${n}？`,
    restoreBody: (n: number, next: number) => `会新建版本 ${next}，内容和版本 ${n} 一样。现有的版本都还在，随时可以再换回来。`,
    restoreConfirm: "恢复",
    onlyOne: "这篇笔记目前只有这一个版本。之后每次编辑、智能体修改或恢复，都会在这里留下一版。",
    loadFailed: "这一版没读出来",
    views: "看这一版的方式",
    preview: "预览",
    compareCurrent: "和当前版本对比",
    comparePrevious: "和上一版对比",
    legendCurrent: "划掉的是后来删掉的，高亮的是后来加上的。",
    legendPrevious: "划掉的是这一版删掉的，高亮的是这一版加上的。",
    sameAsCurrent: "和当前版本没有区别。",
    sameAsPrevious: "和上一版没有区别。",
    unfold: (n: number) => `展开未改动的 ${n} 行`,
    //: 每一版怎么来的(后端 NoteRevisionOut.origin)。
    origins: { create: "新建", edit: "手动编辑", append: "存到笔记", agent: "智能体修改", restore: "恢复", board: "画板写入", workflow: "工作流写入" },
    restoredFrom: (n: number) => `从版本 ${n} 恢复`,
    chars: "字",
    titleChanged: "改了标题",
  },
};
type Strings = typeof zh;
const en: Strings = {
  noteList: "Note list", selectNotes: "Select notes", selectNote: "Select note", cancelSelection: "Cancel selection", selectVisible: "Select current list", selectedCount: (count:number)=>`${count} selected`, noneSelected: "No notes selected yet", batchActions: "Batch actions",
  openNote: "Open note", rename: "Rename", duplicate: "Duplicate", unfavorite: "Remove favorite", copySuffix: "Copy", partialFailure: (count:number)=>`${count} notes could not be updated. Please retry.`,
  referenceVersion: (version:number)=>`Referenced version ${version} · Showing the latest note`, viewReference: "View referenced version",

  actions: "Note actions", close: "Close properties",
  insert: "Insert",
  deleteForever: "Delete permanently", deleteWarning: "This note and all its revisions will be permanently deleted. Existing references will remain, but their source will no longer open.", inTrash: "This note is in trash. Restore it to continue editing.",
  bold: "Bold", italic: "Italic", strike: "Strikethrough", heading: "Paragraph style", paragraph: "Paragraph", headingLevels: ["Heading 1", "Heading 2", "Heading 3", "Heading 4", "Heading 5", "Heading 6"], bulletList: "Bullet list", numberedList: "Numbered list", taskList: "Task list", quote: "Blockquote", code: "Code block", divider: "Divider", image: "Insert image", imageHint: "Or paste / drop it in", uploading: "Uploading image…", undo: "Undo", redo: "Redo", nothingToUndo: "Nothing to undo", nothingToRedo: "Nothing to redo", link: "Web link", apply: "Apply", table: "Table", insertTable: "Insert table", tableSize: (rows:number, cols:number)=>`${rows} × ${cols}`, addRow: "Add row below", addColumn: "Add column right", deleteRow: "Delete row", deleteColumn: "Delete column", deleteTable: "Delete table",
  listEmpty: "No notes yet", listEmptyHint: "Start with one idea. Build a collection as you create.", trashEmpty: "Trash is empty", trashHint: "Notes moved to trash can be restored here.", favoriteEmpty: "No favorites yet", favoriteHint: "Star a note to keep it close for next time.", searchHint: "Try another keyword or clear your filters.", clearSearch: "Clear filters",
  title: "Notes", all: "All notes", favorite: "Favorites", trash: "Trash", topics: "Topics", tags: "Tags",
  new: "New note", search: "Search titles, text or tags", untitled: "Untitled note", empty: "Keep an idea worth returning to",
  emptyHint: "Write a thought, or save an excerpt from a transcript, conversation or board.", noResults: "No notes found",
  saved: "Saved", saving: "Saving…", draft: "Unsaved draft", error: "Save failed. Your draft is kept on this device.", retry: "Retry save",
  conflict: "A newer version exists. Export your local draft before loading the latest version.", reload: "Load latest",
  source: "Sources & properties", history: "Version history", restore: "Restore version", restoreTrash: "Restore from trash", moveTrash: "Move to trash",
  import: "Import Markdown", dropHint: "Drop to import as notes (.md / .markdown / .txt)", importUnsupported: "Only .md, .markdown or .txt files can be imported", imported: (n:number)=>`Imported ${n} notes`, importPartial: (n:number, failed:string[])=>`Imported ${n}; ${failed.length} not imported (over 500 KB or unreadable): ${failed.slice(0,3).join(", ")}${failed.length>3?"…":""}`, export: "Export Markdown", format: "Formatting", moreFormats: "More formatting", versionContent: "Version content", raw: "Markdown", rawHint: "View the Markdown source; click again to go back to editing",
  content: "Note content", placeholder: "Start writing, or type @ to reference a note…", addReference: "Reference a note",
  topicHint: "Topics, separated by commas", tagHint: "Tags, separated by commas", sourcesEmpty: "Excerpts saved from media or conversations link back to their sources here.",
  saveTo: "Save to notes", nothingToSave: "Nothing to save yet", append: "Append to a note", choose: "Choose a note", excerpt: "Excerpt", done: "Saved to notes",
  shape: "Body shape", shapePlain: "Prose", shapeCited: "Quotes with timecodes",
  saveAsNew: "Save as a new note", noteTitle: "Note title", create: "Create", titleHint: "Leave blank to use the opening words as the title.",
  willSave: (chars:number, sources:number)=>`About ${chars} characters and ${sources} source references`,
  saveAll: "Save all to notes", saveAllTranscript: "Save the whole transcript as one note. With a selection, only the selected lines.",
  saveAllSubtitles: "Save the whole subtitle track as one note; translations are written alongside the original.",
  localDraft: "Recovered a local unsaved draft", more: "Load more",
  askAi: "Ask AI", askAiHint: "Ask the assistant about the selected text", passageGone: "That passage has changed since; it was not found in the note.", focus: "Focus on writing", exitFocus: "Show list", unavailable: "Source deleted or unavailable", loading: "Loading…",
  selection: {
    toolbar: "Selection tools", inlineCode: "Inline code", highlight: "Highlight", unlink: "Remove link", linkPlaceholder: "Paste an https:// link and press Enter",
    ai: "AI actions", more: "More", copy: "Copy", copied: "Copied", quote: "Quote in chat", addToBoard: "Add to board",
    readAloud: "Read aloud", stopReading: "Stop reading", readingWithVoice: "Reading aloud with the voice you chose under Voice chat", readingWithEdge: "Reading aloud with the free Edge voice", saveAudio: "Save as audio", savingAudio: "Generating the audio; it will be in the media library",
    actions: {
      polish: { label: "Polish", hint: "Make it read more smoothly without changing the meaning", prompt: "Polish the selected passage" },
      rewrite: { label: "Rewrite", hint: "Say the same thing a different way", prompt: "Rewrite the selected passage" },
      expand: { label: "Expand", hint: "Add details and examples", prompt: "Expand the selected passage" },
      shorten: { label: "Shorten", hint: "Keep only the main points", prompt: "Shorten the selected passage" },
      translate: { label: "Translate", hint: "Chinese to English, anything else to Chinese", prompt: "Translate the selected passage into {lang}" },
      summarize: { label: "Summarize", hint: "Summarize it in the chat without changing the note", prompt: "Summarize the selected passage" },
      explain: { label: "Explain", hint: "Explain it in the chat without changing the note", prompt: "Explain the selected passage" },
      continue: { label: "Continue", hint: "Write the next paragraph and insert it after this one", prompt: "Continue writing after the selected passage" },
    },
    languages: { en: "English", zh: "Chinese" },
  },
  board: {
    title: "Add to board", search: "Search boards", empty: "No boards yet", noMatch: "No board by that name", loading: "Loading boards…",
    newBoard: "New board", newBoardNamed: (name: string) => `New board “${name}”`, defaultName: "New board",
    added: (name: string) => `Added to board “${name}”`, open: "Open board",
  },
  node: {
    imageLink: "Image address",
    alt: "Alternative text",
    apply: "Apply image changes",
    cancel: "Cancel image changes",
    invalid: "Use an https:// image address or an existing media reference.",
    unavailable: "Image unavailable",
    preview: "View full size",
    previewOf: (n: number) => `Note image ${n}`,
    language: "Code language",
    plain: "Plain text",
    copy: "Copy code",
    copied: "Copied",
    failed: "Could not copy. Select the code and copy it manually.",
  },
  versions: {
    hint: "Restoring creates a new version; every existing version stays.",
    list: "Versions",
    current: "Current version",
    version: (n: number) => `Version ${n}`,
    today: "Today",
    yesterday: "Yesterday",
    copy: "Copy this version's content",
    copied: (n: number) => `Copied the text of version ${n}`,
    restore: "Restore this version",
    restoreTitle: (n: number) => `Restore version ${n}?`,
    restoreBody: (n: number, next: number) => `This creates version ${next} with the same content as version ${n}. Every existing version stays, so you can switch back at any time.`,
    restoreConfirm: "Restore",
    onlyOne: "This note has only this one version so far. Every edit, assistant change or restore from now on leaves a version here.",
    loadFailed: "This version could not be loaded",
    views: "How to view this version",
    preview: "Preview",
    compareCurrent: "Compare with current",
    comparePrevious: "Compare with previous",
    legendCurrent: "Struck-through text was removed later; highlighted text was added later.",
    legendPrevious: "Struck-through text was removed in this version; highlighted text was added in it.",
    sameAsCurrent: "No difference from the current version.",
    sameAsPrevious: "No difference from the previous version.",
    unfold: (n: number) => `Show ${n} unchanged lines`,
    origins: { create: "Created", edit: "Edited", append: "Saved to note", agent: "Changed by the assistant", restore: "Restored", board: "Written from a board", workflow: "Written by a workflow" },
    restoredFrom: (n: number) => `Restored from version ${n}`,
    chars: "chars",
    titleChanged: "Title changed",
  },
};
export function noteStrings(locale: string) { return locale === "en-US" ? en : zh; }
export function useNoteStrings() { return noteStrings(usePreferences().locale); }
