"""初始表结构:账号、会话与刷新令牌、设备授权、短信验证码、工作流与插件、画板分享、文件。

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 10:42:31.753747
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sha256', name=op.f('pk_blobs'))
    )
    op.create_table('rate_counters',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_rate_counters'))
    )
    op.create_table('sms_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_codes'))
    )
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.create_index('ix_sms_codes_ip_created', ['ip', 'created_at'], unique=False)
        batch_op.create_index('ix_sms_codes_phone_created', ['phone', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('avatar_sha256', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('handle_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.String(length=32), nullable=True),
    sa.Column('terms_agreed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('handle', name=op.f('uq_users_handle')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    op.create_table('blob_owners',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sha256'], ['blobs.sha256'], name=op.f('fk_blob_owners_sha256_blobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blob_owners_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'sha256', name=op.f('pk_blob_owners'))
    )
    op.create_table('device_authorizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_code', sa.String(length=9), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_authorizations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_authorizations')),
    sa.UniqueConstraint('device_code_hash', name=op.f('uq_device_authorizations_device_code_hash')),
    sa.UniqueConstraint('user_code', name=op.f('uq_device_authorizations_user_code'))
    )
    op.create_table('items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('plugin_id', sa.String(length=160), nullable=True),
    sa.Column('title', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_sha256', sa.String(length=64), nullable=True),
    sa.Column('official', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('downloads_total', sa.Integer(), nullable=False),
    sa.Column('likes_total', sa.Integer(), nullable=False),
    sa.Column('views_total', sa.Integer(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_items_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('kind', 'slug', name=op.f('uq_items_kind_slug')),
    sa.UniqueConstraint('plugin_id', name=op.f('uq_items_plugin_id'))
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_items_kind_created', ['kind', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_owner_id'), ['owner_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('reporter_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_id'), ['target_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('shares',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('board_key', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_shares_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shares')),
    sa.UniqueConstraint('owner_id', 'board_key', name=op.f('uq_shares_owner_id_board_key')),
    sa.UniqueConstraint('slug', name=op.f('uq_shares_slug'))
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shares_owner_id'), ['owner_id'], unique=False)

    op.create_table('item_daily_stats',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_daily_stats_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'day', name=op.f('pk_item_daily_stats'))
    )
    with op.batch_alter_table('item_daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_daily_stats_day'), ['day'], unique=False)

    op.create_table('item_tags',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_tags_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag', name=op.f('pk_item_tags'))
    )
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_tags_tag'), ['tag'], unique=False)

    op.create_table('item_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitter_id', sa.String(length=32), nullable=False),
    sa.Column('file_key', sa.String(length=400), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('localized_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('external_download', sa.String(length=500), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_versions_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], name=op.f('fk_item_versions_submitter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_versions')),
    sa.UniqueConstraint('item_id', 'number', name=op.f('uq_item_versions_item_id_number')),
    sa.UniqueConstraint('item_id', 'version', name=op.f('uq_item_versions_item_id_version'))
    )
    with op.batch_alter_table('item_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_versions_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_item_versions_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_versions_submitter_id'), ['submitter_id'], unique=False)

    op.create_table('likes',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_likes_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('pk_likes'))
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_item_id'), ['item_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pair_iat', sa.BigInteger(), nullable=False),
    sa.Column('pair_role', sa.String(length=16), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('successor_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_refresh_tokens_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_session_id'), ['session_id'], unique=False)

    op.create_table('share_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('share_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('og_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], name=op.f('fk_share_versions_share_id_shares'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_versions')),
    sa.UniqueConstraint('share_id', 'number', name=op.f('uq_share_versions_share_id_number'))
    )
    with op.batch_alter_table('share_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_versions_share_id'), ['share_id'], unique=False)

    op.create_table('share_version_blobs',
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sha256'], ['blobs.sha256'], name=op.f('fk_share_version_blobs_sha256_blobs')),
    sa.ForeignKeyConstraint(['version_id'], ['share_versions.id'], name=op.f('fk_share_version_blobs_version_id_share_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'sha256', name=op.f('pk_share_version_blobs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_version_blobs')
    with op.batch_alter_table('share_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_versions_share_id'))
        batch_op.drop_index(batch_op.f('ix_share_versions_created_at'))

    op.drop_table('share_versions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_session_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_item_id'))

    op.drop_table('likes')
    with op.batch_alter_table('item_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_versions_submitter_id'))
        batch_op.drop_index('ix_item_versions_status_created')
        batch_op.drop_index(batch_op.f('ix_item_versions_item_id'))

    op.drop_table('item_versions')
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_tags_tag'))

    op.drop_table('item_tags')
    with op.batch_alter_table('item_daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_daily_stats_day'))

    op.drop_table('item_daily_stats')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_owner_id'))

    op.drop_table('shares')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_target_id'))
        batch_op.drop_index('ix_reports_status_created')

    op.drop_table('reports')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_owner_id'))
        batch_op.drop_index('ix_items_kind_created')

    op.drop_table('items')
    op.drop_table('device_authorizations')
    op.drop_table('blob_owners')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_sms_codes_phone_created')
        batch_op.drop_index('ix_sms_codes_ip_created')

    op.drop_table('sms_codes')
    op.drop_table('rate_counters')
    op.drop_table('blobs')
    # ### end Alembic commands ###
