export const IPC: {
  readonly invoke: Readonly<{
    checkUpdates: "mosael:check-updates";
    mainStatus: "mosael:main-status";
    restartMain: "mosael:restart-main";
    recordingStatus: "recording-permissions:status";
    recordingRequest: "recording-permissions:request";
    recordingOpenSettings: "recording-permissions:open-settings";
    getOpenAtLogin: "system:getOpenAtLogin";
    setOpenAtLogin: "system:setOpenAtLogin";
    customCssRead: "customCss:read";
    customCssPath: "customCss:path";
    customCssOpen: "customCss:open";
    customCssReveal: "customCss:reveal";
    publishLogin: "publish:login";
    publishOpenPage: "publish:openPage";
    publishInspect: "publish:inspect";
    publishNavigate: "publish:navigate";
    publishBack: "publish:back";
    publishForward: "publish:forward";
    publishReload: "publish:reload";
    publishHideView: "publish:hideView";
    publishPanelLayout: "publish:panelLayout";
    publishClosePanel: "publish:closePanel";
    publishPanelMuted: "publish:panelMuted";
    publishSwitchPage: "publish:switchPage";
    publishClosePage: "publish:closePage";
    publishReorderPages: "publish:reorderPages";
    publishNewPage: "publish:newPage";
    publishPagesInset: "publish:pagesInset";
    publishSnapshotPage: "publish:snapshotPage";
    publishCoverPage: "publish:coverPage";
    publishFocusPage: "publish:focusPage";
    browserOpenLogin: "browser:openLogin";
    publishSignOut: "publish:signOut";
    browserClearProfile: "browser:clearProfile";
    comfyuiOpenWorkflow: "comfyui:openWorkflow";
    comfyuiNewWorkflow: "comfyui:newWorkflow";
    pageToolsCapture: "pageTools:capture";
    pageToolsRegionStart: "pageTools:regionStart";
    pageToolsRegionFinish: "pageTools:regionFinish";
    pageToolsVideos: "pageTools:videos";
    pageToolsImages: "pageTools:images";
    pageToolsFetchImages: "pageTools:fetchImages";
    pageToolsRead: "pageTools:read";
    pageToolsInset: "pageTools:inset";
    pageToolsSaveDownload: "pageTools:saveDownload";
    dataExportDiagnostics: "data:exportDiagnostics";
    dataCreateBackup: "data:createBackup";
    dataApplyRestore: "data:applyRestore";
  }>;
  readonly send: Readonly<{
    titleOverlay: "mosael:title-overlay";
    systemStatus: "system:status";
    systemNotify: "system:notify";
    locale: "mosael:locale";
    floatShow: "float:show";
    floatHide: "float:hide";
  }>;
  readonly event: Readonly<{
    fullscreen: "mosael:fullscreen";
    openTasks: "mosael:open-tasks";
    deepLink: "mosael:deep-link";
    openFiles: "mosael:open-files";
    updateAvailable: "mosael:update-available";
    mainStale: "mosael:main-stale";
    customCss: "mosael:custom-css";
    publishView: "publish:view";
    publishPanels: "publish:panels";
    browserFrame: "browser:frame";
    pageToolsDownload: "pageTools:download";
  }>;
};

export function parsePublishTarget(value: unknown, channel: string): { accountId: string; platform: string };
export function parseAuthToken(value: unknown, channel: string): { token: string };
export function parseRestoreStage(value: unknown): { stageId: string };
export function parseUrlRequest(value: unknown, channel: string): { url: string };
export function parsePanelId(value: unknown): { id: string };
export function parsePanelMuted(value: unknown): { id: string; muted: boolean };
export function parsePanelLayout(value: unknown): import("./preload-api").LivePanelLayoutChange;
export function parseBrowserProfile(value: unknown): { partition: string };
export function parseBrowserLogin(value: unknown): {
  resume: boolean;
  partition: string;
  url: string;
  name: string;
  proxy: string | null;
};
export function parseComfyWorkflow(value: unknown): { partition: string; url: string; name: string; path: string };
export function parseComfyNewWorkflow(value: unknown): { partition: string; url: string; name: string };
export function parseTitleOverlay(value: unknown): { color: string; symbolColor: string };
export function parseSystemStatus(value: unknown): { runningJobs: number; progress?: number | null };
export function parseTaskNotice(value: unknown): { title: string; body: string };
export function parseLocale(value: unknown): { locale: string };
export function parseCaptureMode(value: unknown): { mode: "visible" | "full" };
export function parseRegionSelection(value: unknown): {
  selection: { x: number; y: number; width: number; height: number } | null;
};
export function parseImageUrls(value: unknown): { urls: string[] };
export function parseReadMode(value: unknown): { mode: "article" | "selection" };
export function parseToolsInset(value: unknown): { right: number };
export function parsePageId(value: unknown, channel: string): { id: string };
export function parsePageOrder(value: unknown): { ids: string[] };
export function parseNewPage(value: unknown): { url: string };
export function parsePagesInset(value: unknown): { left: number };
export function parseCoverPage(value: unknown): { covered: boolean };
export function parseFloatShow(value: unknown): {
  id: string;
  html: string;
  rect: { x: number; y: number; width: number; height: number };
  root: { className: string; style: string; attributes: Record<string, string> };
};
export function parseFloatHide(value: unknown): { id: string | null };
export function parseSaveDownload(value: unknown): {
  id: string;
  server: string;
  token: string;
  workspaceId: string;
  projectId: string | null;
};
