"""请求/响应体的**唯一装配入口**(棘轮:tests/test_domain_assembly_entries.py)。

schema 按领域切在这个包下的各个文件里,这里只把它们收到一处:路由一律
`from app.api.schemas import X`,继续切文件不会扩散到全仓(见 docs/ARCHITECTURE.md
「文件布局可以按领域切片,但切片不是公共 Interface」)。

这个文件里**不定义任何东西** —— 它一旦开始长自己的类,切片就又变回了半个入口。
"""

from __future__ import annotations

from app.api.schemas.base import ApiModel, CostAmountOut, OrmModel  # noqa: F401
from app.api.schemas.agent import AgentCompactOut, AgentContextOut, AgentContextPart, AgentManifestOut, AgentMemoryCreate, AgentMemoryOut, AgentMemoryUpdate, AgentMessageCreate, AgentMessageOut, AgentMessageQuoteIn, AgentPendingView, AgentPlanUpdate, AgentQuestionAnswer, AgentQuestionCreate, AgentQuestionItem, AgentQuestionOption, AgentQuestionOut, AgentReferenceIn, AgentSessionCreate, AgentSessionOut, AgentSessionUpdate, AgentSkillOut, AgentStreamEvent, ConfirmationCreate, ConfirmationOut, SessionAllowance, SessionGroupCreate, SessionGroupOut, SessionGroupUpdate  # noqa: F401
from app.api.schemas.boards import BoardCreate, BoardDuplicate, BoardNoteAppend, BoardNoteAppendOut, BoardOut, BoardSourceNote, BoardPreview, BoardPreviewEdge, BoardPreviewItem, BoardProducerOut, BoardRun, BoardSequenceCreate, BoardSequenceOut, BoardSummaryOut, BoardUpdate  # noqa: F401
from app.api.schemas.browser import (  # noqa: F401
    BrowserProfileCreate,
    BrowserProfileOpened,
    BrowserProfileOut,
    BrowserProfileUpdate,
    BrowserSessionOut,
    BrowserSessionRunOut,
)
from app.api.schemas.capabilities import CapabilityChoicesOut, CapabilityDefaultUpdate, CapabilityProviderOut, CapabilityTermOut, CapabilityUseOut  # noqa: F401
from app.api.schemas.collaboration import ActivityOut, ActorOut, CanvasCommentAnchor, CommentAnchorUpdate, CommentContentUpdate, CommentCreate, CommentOut  # noqa: F401
from app.api.schemas.dashboard import AdminOverviewOut, DailyActivityOut, DailyPublishOut, DailyUsageOut, DailyUsageTokensOut, DaySeriesPoint, UnpricedUsageOut, UserSpendPoint, WorkspaceSummaryOut  # noqa: F401
from app.api.schemas.entities import AssetEntityOut, EntityCatalogOut, EntityConsentKindOut, EntityCreate, EntityDrawRequest, EntityKindOut, EntityLostReferenceOut, EntityOut, EntityReferenceAdd, EntityReferenceOrder, EntityReferenceOut, EntityReferenceUpdate, EntityRoleOut, EntitySummaryOut, EntityUpdate, EntityUsageBoardOut, EntityUsageGenerationOut, EntityUsageOut, EntityUsageWorkflowOut, EntityVariantCreate  # noqa: F401
from app.api.schemas.feishu import FeishuBindCodeOut, FeishuBindingOut, FeishuBotCreate, FeishuBotOut, FeishuBotUpdate, FeishuOnboardingOut  # noqa: F401
from app.api.schemas.generation import CapabilityProfileFieldOut, CapabilityProfileSchemaOut, GenerationCapabilityProfileCreate, GenerationCapabilityProfileOut, GenerationCapabilityProfileUpdate, GenerationCreate, GenerationCreateResponse, GenerationJobOut, GenerationModelOut, GenerationOptionOut, GenerationSessionCreate, GenerationSessionOut, GenerationSessionUpdate, PromptOptimizeRequest, PromptOptimizeResponse, SourceAssetRef  # noqa: F401
from app.api.schemas.identity import AdminUserOut, AuthCredentials, AuthOut, BootstrapOut, DeploymentAdminUpdate, InvitationListOut, InvitationOut, InviteCreate, InviteMemberRequest, MembersOut, PasswordUpdate, RegisterCredentials, RenameRequest, SetRoleRequest, UserOut, UserProfileUpdate, WorkspaceCreate, WorkspaceMemberOut, WorkspaceOut  # noqa: F401
from app.api.schemas.jobs import JobKindCatalogOut, JobKindOut, JobOut, TaskEventOut  # noqa: F401
from app.api.schemas.media import AnalyzeAssetRequest, AnalyzeAssetResponse, AssetExtractionOut, DocumentNoteOut, DocumentTextOut, DocumentPagesRequest, DocumentParseRequest, ExtractionSectionOut, ExtractionSectionsOut, AssetFrameRequest, AssetDerivationOut, AssetLineageNode, AssetLineageOut, AssetOut, AssetUpdate, DenoiseAssetRequest, FontOut, LocalImportRequest, LutOut, LutUpdate, RemoteEntryOut, UrlImportItem, UrlImportRequest, UrlProbeRequest, UrlProbeResponse, UrlSupportResponse, VideoToGifRequest  # noqa: F401
from app.api.schemas.notes import NoteAppend, NoteCreate, NoteOut, NotePageCreate, NoteReferenceOut, NoteRestore, NoteRevisionOut, NoteUpdate  # noqa: F401
from app.api.schemas.notifications import NotificationListOut, NotificationOut, NotifyRequest  # noqa: F401
from app.api.schemas.plugins import WorkflowGraphNodeOut, WorkflowGraphGroupOut, WorkflowGraphOut, WorkflowInputOut, WorkflowParameterOut, WorkflowOutputOut, WorkflowModelRefOut, WorkflowNodePackOut, WorkflowMissingNodeOut, WorkflowMissingModelOut, WorkflowGenerationRefOut, WorkflowLastOutputOut, WorkflowUseOut, WorkflowFileOut, WorkflowOtherFileOut, WorkflowTrashedOut, WorkflowManagerOut, WorkflowEditorOut, WorkflowLibraryImportRequest, WorkflowLibraryImportOut, WorkflowLibrarySaveRequest, WorkflowInstallNodesRequest, WorkflowRebootOut, WorkflowContentOut, WorkflowCopyRequest, WorkflowLibraryOut, WorkflowPathOut, WorkflowRenameRequest, WorkflowRestoreRequest, WorkflowTrashRequest, MissingModelOut, ModelDetailOut, ModelDownloadRequest, ModelDownloadRouteOut, ModelFileOut, ModelLibraryFolderOut, ModelLibraryOut, ModelLibraryRefOut, ModelResolveOut, ModelResolveRequest, ModelTagOut, PluginCapabilityStatusOut, PluginCapabilityUseOut, PluginCapabilityUpdate, PluginCredentialOut, PluginCredentialUpdate, PluginFieldOut, PluginInstallPreview, PluginInstallRequest, PluginInstanceCreate, PluginInstanceOut, PluginInstanceUpdate, PluginInvocationOut, PluginInvokeRequest, PluginMarketEntry, PluginMarketOut, PluginMarketTool, PluginNetworkOut, PluginNetworkUpdate, PluginPackageSourceOut, PackageSourcePresetOut, PluginOAuthCode, PluginOAuthOut, PluginPackageOut, PluginPermissionGrantOut, PluginPermissionGrantUpdate, PluginProvidedInputOut, PluginProvidedModelOut, PluginProvidedParameterOut, PluginToolOut, PluginToolStateOut  # noqa: F401
from app.api.schemas.projects import ProjectCreate, ProjectOut, ProjectWithStatsOut  # noqa: F401
from app.api.schemas.providers import CapabilityModelOut, OAuthAnswerIn, OAuthLoginOut, OAuthPromptOut, PricingPrefillOut, PricingTimeWindow, ProviderCredentialIn, ProviderCredentialOut, ProviderDefaultOut, ProviderDefaultUpdate, ProviderHealthOut, ProviderModelOut, ProviderModelUpdate, ProviderPricingRuleCreate, ProviderPricingRuleOut, ProviderPricingRuleUpdate, ProviderProfileCreate, ProviderProfileOut, ProviderProfileUpdate, ProviderQuotaMetricOut, ProviderQuotaOut, ProviderUsageEventOut, VendorFieldOut, VendorPresetOut  # noqa: F401
from app.api.schemas.publish import PublishAccountCreate, PublishAccountOut, PublishAccountUpdate, PublishCopyRequest, PublishCopyResponse, PublishCreate, PublishOptionChoice, PublishOptionSpec, PublishPlatformOut, PublishTaskOut, PublishedPostOut  # noqa: F401
from app.api.schemas.runtime_config import AiRuntimeConfigOut, AiRuntimeConfigUpdate, AsrModelOut, DenoiseEngineOut, InstallSourceOut, InstallSourceUpdate, NetworkConfigOut, NetworkConfigUpdate, SeparationEngineOut, TtsConfigOut, TtsConfigUpdate, TtsEngineChoiceOut, TtsEngineOut  # noqa: F401
from app.api.schemas.scenes import SceneCreate, SceneOperations, SceneOut, SceneReferenceOut, SceneReferenceRequest, SceneUpdate  # noqa: F401
from app.api.schemas.scheduler import RunScheduledTaskResponse, ScheduledTaskCreate, ScheduledTaskOut, ScheduledTaskRunOut, ScheduledTaskUpdate  # noqa: F401
from app.api.schemas.sequences import AddTrackRequest, AppendAssetRequest, ClipAudioRequest, ClipIdsRequest, ClipMoveEntry, ClipOut, ClipPointSplitsRequest, ClipRangeCutsRequest, ClipTextEntry, CutClipRangeRequest, CutClipRangesBatchRequest, CutClipRangesRequest, DuplicateClipsRequest, ExportRequest, GenerateSubtitlesRequest, InsertClipRequest, InsertTextClipRequest, MoveClipRequest, MoveClipsBatchRequest, MoveTrackRequest, ReplaceClipMediaRequest, RippleDeleteClipsRequest, SequenceCreate, SequenceDuplicate, SequenceFrameRequest, SequenceOut, SequenceRename, SetClipEffectsRequest, SetClipGainRequest, SetClipSpeedRequest, SetClipTextRequest, SetClipTextsRequest, SetClipTransformRequest, SetSequenceReframeRequest, SetSubtitleStyleRequest, SetTrackStateRequest, SplitClipPointsBatchRequest, SplitClipPointsRequest, SplitClipRequest, SubtitleCueInput, SubtitleImportOut, TrackOut, TrimClipRequest  # noqa: F401
from app.api.schemas.transcripts import TranscriptAttachRequest, TranscriptOut, TranscriptSegmentIn, TranscriptSegmentOut, TranscriptTokenIn, TranscriptTokenOut  # noqa: F401
from app.api.schemas.translate import TranslateRequest, TranslateResponse  # noqa: F401
from app.api.schemas.voices import AgentSpeechRequest, AgentVoiceOut, AgentVoiceUpdate, EngineSynthesizeRequest, VoicePreviewRequest, PodcastRequest, SubtitleDubRequest, SynthesizeRequest, TtsVoiceOut, VoiceFromSpeakerRequest, VoiceOut, VoiceUpdate  # noqa: F401
from app.api.schemas.workflows import WorkflowAiEditRequest, WorkflowAiEditResponse, WorkflowCreate, WorkflowFieldOptionOut, WorkflowFromPage, WorkflowImportRequest, WorkflowNodeTypeOut, WorkflowOut, WorkflowRevisionDetailOut, WorkflowRevisionOut, WorkflowRunOutputOut, WorkflowRunRequest, WorkflowTemplateCheckOut, WorkflowTemplateOut, WorkflowTemplateRequirementOut, WorkflowUnusableNodeOut, WorkflowUpdate  # noqa: F401
