#!/usr/bin/env python3
"""把仓库里的棘轮测试清单生成进 docs/CONVENTIONS.md。

手写的清单会腐烂,而且**没有任何信号**。上一版清单写在 IMPLEMENTATION_STATUS.md 里,列了
7 条 —— 实际有 30 条,缺的正是后来加的那批。读者据此以为这个仓库只守着 7 件事。

判据是显式的:测试模块里写了 `RATCHET = True`(Python)或 `export const RATCHET = true;`
(TypeScript)才算。摘要取模块开头那段说明的第一行 —— 那句话本来就是写给人读的,不必为了
生成再复述一遍。

用法:
    python3 scripts/sync-ratchet-docs.py            # 写回文档
    python3 scripts/sync-ratchet-docs.py --check    # 只校验,过期则非零退出
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "CONVENTIONS.md"

BEGIN = "<!-- BEGIN RATCHETS (generated by scripts/sync-ratchet-docs.py — do not edit by hand) -->"
END = "<!-- END RATCHETS -->"

# 扫描范围。写死成两处,免得哪天有人把测试放进 node_modules 之类的地方还被收进来。
PY_ROOTS = [ROOT / "backend" / "tests"]
TS_ROOTS = [ROOT / "frontend" / "src"]


def _tidy(line: str) -> str:
    """摘要落进表格前的整理:去掉行尾冒号,转义竖线(否则会把表格切断)。"""
    return line.strip().rstrip(":：").replace("|", "\\|")


def collect_python() -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for root in PY_ROOTS:
        for path in sorted(root.rglob("test_*.py")):
            source = path.read_text(encoding="utf-8")
            if "RATCHET = True" not in source:
                continue
            tree = ast.parse(source)
            # 只认模块顶层的赋值,别把某个函数里的同名局部变量当成标记。
            marked = any(
                isinstance(node, ast.Assign)
                and any(isinstance(t, ast.Name) and t.id == "RATCHET" for t in node.targets)
                for node in tree.body
            )
            if not marked:
                continue
            doc = ast.get_docstring(tree)
            if not doc:
                raise SystemExit(f"{path.relative_to(ROOT)}: 标了 RATCHET 却没有模块说明")
            found.append((str(path.relative_to(ROOT)), _tidy(doc.splitlines()[0])))
    return found


TS_DOC = re.compile(r"^/\*\*\s*\n\s*\*\s*(?P<first>.+?)\s*$", re.M)


def collect_typescript() -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for root in TS_ROOTS:
        for path in sorted(root.rglob("*.test.ts*")):
            source = path.read_text(encoding="utf-8")
            if "export const RATCHET = true" not in source:
                continue
            match = TS_DOC.match(source)
            if not match:
                raise SystemExit(f"{path.relative_to(ROOT)}: 标了 RATCHET 却没有开头的 /** */ 说明")
            found.append((str(path.relative_to(ROOT)), _tidy(match.group("first"))))
    return found


def render() -> str:
    rows = ["| 守住什么 | 测试 |", "| --- | --- |"]
    for label, group in (("后端", collect_python()), ("前端", collect_typescript())):
        for path, summary in group:
            rows.append(f"| {summary} | `{path}` |")
        if label == "后端":
            rows.append("| | |")  # 两侧之间留一条空行,读的时候分得清
    total = len(collect_python()) + len(collect_typescript())
    head = f"共 {total} 道。清单由脚本生成 —— 给测试加上 `RATCHET` 标记它就会出现在这里。"
    return "\n".join([BEGIN, "", head, "", *rows, "", END])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="只校验,不写回")
    args = parser.parse_args()

    current = DOC.read_text(encoding="utf-8")
    if BEGIN not in current or END not in current:
        print(f"{DOC.relative_to(ROOT)} 里找不到生成区标记", file=sys.stderr)
        return 1

    before, rest = current.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    updated = before + render() + after

    if updated == current:
        return 0
    if args.check:
        print(
            "docs/CONVENTIONS.md 的棘轮清单已过期。重新生成:\n"
            "    python3 scripts/sync-ratchet-docs.py",
            file=sys.stderr,
        )
        return 1
    DOC.write_text(updated, encoding="utf-8")
    print(f"已更新 {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
