/**
 * 两份极小的真实代理文件(ffmpeg 按后端 media/proxy.py 的配方生成,faststart):
 *
 * - TINY_AUDIO_PROXY:0.5s 440Hz 正弦,AAC-LC 48kHz 立体声(音频代理的格式)。
 * - TINY_VIDEO_PROXY:0.6s 64×64 testsrc,10fps,H.264 GOP=3、无 B 帧(画面代理的格式)。
 *
 * 用来验证样本表是从**真文件**里读出来的(偏移、关键帧、编辑列表的预延迟),而不是从桩里。
 */
export const TINY_AUDIO_PROXY = base64Bytes(
  "AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAA15tb292AAAAbG12aGQAAAAAAAAAAAAAAAAAALuAAABdwAABAAABAAAA" +
  "AAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC" +
  "AAACiXRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAABdwAAAAAAAAAAAAAAAAQEAAAAAAQAAAAAAAAAAAAAAAAAA" +
  "AAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAXcAAAAQAAAEAAAAAAgFtZGlh" +
  "AAAAIG1kaGQAAAAAAAAAAAAAAAAAALuAAABhwFXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAAAAAAAAAAAAAAAFNvdW5kSGFu" +
  "ZGxlcgAAAAGsbWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAFwc3Ri" +
  "bAAAAGpzdHNkAAAAAAAAAAEAAABabXA0YQAAAAAAAAABAAAAAAAAAAAAAgAQAAAAALuAAAAAAAA2ZXNkcwAAAAADgICAJQAB" +
  "AASAgIAXQBUAAAAAAH0AAAB83AWAgIAFEZBW5QAGgICAAQIAAAAgc3R0cwAAAAAAAAACAAAAGAAABAAAAAABAAABwAAAABxz" +
  "dHNjAAAAAAAAAAEAAAABAAAAGQAAAAEAAAB4c3RzegAAAAAAAAAAAAAAGQAAAFQAAAB8AAAASAAAAEcAAABYAAAAWAAAAEkA" +
  "AABZAAAAWAAAAEsAAABaAAAASAAAAEwAAABNAAAAWAAAAFoAAABbAAAASQAAAF4AAABHAAAAXgAAAEoAAABgAAAASwAAAEYA" +
  "AAAUc3RjbwAAAAAAAAABAAADigAAABpzZ3BkAQAAAHJvbGwAAAACAAAAAf//AAAAHHNiZ3AAAAAAcm9sbAAAAAEAAAAZAAAA" +
  "AQAAAGF1ZHRhAAAAWW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALGlsc3QAAAAkqXRvbwAA" +
  "ABxkYXRhAAAAAQAAAABMYXZmNjMuMS4xMDIAAAAIZnJlZQAACCttZGF03ABMYXZjNjMuMS4xMDIAQkqqWDE9audePN3qalyL" +
  "sBBEFJlqi18mhgmmmy8aqqvlNNl48ePH5ZZoouPHj8suWKLjSjVaudePN3qalyLsAAAAAAOAIUVs///8xZKWRlkpZSN/r1x4" +
  "/1/fzq//j9/Ovb/6fjzobU7NuuYzBqpOqzuaW9FKdMlZWiw7H8tl/5bBFGgIbemQSCied11piOarEQhiZ8omfKJhKhywn4Dz" +
  "izgSEzA0aNGt/r1x4/1/fzq//j9/Ovb/6fjzoAAAAAABwCF1lMlZk/j+n69cceeJ1NNNXoH/htL7nx8Zm3ff3B/j4Mn39wPj" +
  "4A9/eEfHxmHv7wg8yNmT+P6fr1xx54nU001egAAAAAADgCEVlAFMRue/+P/4v/L/f/eF6peeeShFFEtegxoooooou6KKIiii" +
  "QiqJ9CKkIKjqgBs57/4//i/8v9/94Xql555KAAAAAAAcIRWUCURK3z/0/+v+3/t/yqSRxVK4xoZkD8YM2SPw+m7chCiL6bvp" +
  "Qyig1AMbdutYRtYU8d5pbowI2b5/6f/X/b/2/5VJI4qlcY0MyB+MGbJH4AAAAAABwCEVlBFZzz/f/6/z/+n+dpdcFcc3DQzI" +
  "5AAZvkUB8p50nY2eeeec/McT7J5p55wedQWgRoinCscssENnPP9//r/P/6f52l1wVxzcNDMjkABm+RQAAAAAAAchFZQBSEjv" +
  "v+//1/n/9P87XJZnXNdch5546VR9bzzzzz1zO/veSx5bEvPJzTlaxKSAGzvv+//1/n/9P87XJZnXNdcgAAAAAAOAIRWT8Vnf" +
  "f/T/6/7/+X+11JxSXUxGhmR8BwzaAACijpQhhFRRRR0UdNHQagxsG9YFZka1FgZYVBhW/DZ33/0/+v+//l/tdScUl1MRoZkf" +
  "AcM2gAAAAAAAADghFZQJWb7/4//i/8v9/94S413574lNDMjgDBm8eAXyiiWvaY0UURRRREURFFEgBCAgBWWZkQSgoEbN9/8f" +
  "/xf+X+/+8Jca7898SmhmRwBgzePAIAAAAAAOIRWUEUBM3z/f/6/z/8/74vL4rWRvjY+nn5vyKLH6fT6fRjIBzvMg+mtwlKUm" +
  "xGUpkuiCGzfP9//r/P/z/vi8vitZG+NgAAAAAAOAIRWUCVnPf+v/7fv/+X+m0amq31zd8tDMjZAhmwBwXNPOk7GHnnnnnnUq" +
  "eec86mlzKUdpQJf9QAKxAjZz3/r/+37//l/ptGpqt9c3fLQzI2QIZsAcEAAAAAAHIRWT6pkUJnjv/j+3H/v/vCW1VXVAaarT" +
  "fX/5ZawMDAyKMWLqsGQNGwrWnLNLLdKio5H0bPHf/H9uP/f/eEtqquqAAAAAAAHAIRWUAUxG57/6f/X/y/3/5Veq1XHOnPnk" +
  "a6KEItIqKKKKKKKKDUUUUG6GqDn81ImjYdEANnPf/T/6/+X+//Kr1Wq450588gAAAAAAOCEVlAlZvn/j/+L/P/n/yTWXXG9b" +
  "1OR8vl8nVsNX8vl8suX5ZT5YgXHm2K/wiCEAsZ1KBziBGzfP/H/8X+f/P/kmsuuN63qcgAAAAAAOIRWUE5ig5f1/4+v/b+dp" +
  "caVKkNDMgYDhm0RwGWNXVtbo/r8qFLzzz30eY8x57neeWIGJCGDE7ywD+SYIbOX9f+Pr/2/naXGlSpDQzIGA4ZtEcAAAAAAA" +
  "HCEVk/lISO+/9f/2/f/7f7ZJnGk51kU0MyMQOGbw/BTzzyPsumn9f1Oo8/r+jzn/X6WpR8G9TRSlig/jZ33/r/+37//b/bJM" +
  "40nOsimhmRiBwzeH4IAAAAAAOCEVk/lZ33/x//F/1/6/73Uku6qTfnloZkcEYM3yAOiiiWuExoooouUUkUXLlEhHehgKKVgC" +
  "cdtxHOH8bO+/+P/4v+v/X/e6kl3VSb88tDMjgjBm+QBwAAAAAAchFZQKEgZPc8/t/8fz/3/W6klom7gBM03nCz0zvHKiiijX" +
  "RuoobooMu0UGStawSzMBjpECNnPP7f/H8/9/1upJaJu4AAAAAAAcIRWUExig3z/H/b9f+/+lVF6XvWZ1toZkYA0M2CAAdnYj" +
  "Cuv+toN17OafZOFT82WeHZ8p0fI6kBQUfUhQPKIIbN8/x/2/X/v/pVRel71mdbaGZGANDNggAAAAAAAA4CEVlAuYliVzz+n/" +
  "b8f+X+OZLS5hWgq6uranR83yo0vPPPJeeeeeeS88tyYxkZSqm5oEbOef0/7fj/y/xzJaXMK0AAAAAAAcIRWT5BkUJnjn+P/T" +
  "/H/f9ZU1VyTaSNDMjEgBm/xgDgDAMDp49ddH2FR48GFkiQYkpLPYVi2yeilGm5btdft1Pg2eOf4/9P8f9/1lTVXJNpI0MyMS" +
  "AGb/GAAAAAAAByEVlAuYoOd/9v6f6fv/yS13XPCuORjMTEoj2tCDGiiiiiiyxRRRcYiQIiQSogR01RAEIEbOd/9v6f6fv/yS" +
  "13XPCuOQAAAAAAHAIRWP//fwLEoSJAImb5/b/j7/9/8Yi5M1ucY0MyOQAGb4FAM7Ozhim6HBn9LRCQkJKpWmqgTdKtJ+p0WI" +
  "lppc7QIvAImb5/b/j7/9/8Yi5M1ucY0MyOQAGb4FAAAAAAAHIRWU7CUam6/p+PhKtppa5IKiYwQtOnw08CThttttltwAAAq0" +
  "PD12AAAq0PD23AABhw8PbcAAGHD50bJuv6fj4SraaWuSAAAAAAAOIRWU0xye7T10ed6tppdpAeNOOOM1uGC44tmd9/eE/x8G" +
  "T7+5H+PhtPv76D/Hw2Pf3hHx8NzQ2dp66PO9W00u0gAAAAAADg==",
);

export const TINY_VIDEO_PROXY = base64Bytes(
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAANDbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAAlgAAQAA" +
  "AQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAgAAAm50cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAAlgAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA" +
  "AAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAEAAAABAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAJYAAAAAAABAAAAAAHm" +
  "bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAoAAAAGABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl" +
  "b0hhbmRsZXIAAAABkW1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAA" +
  "AQAAAVFzdGJsAAAAvXN0c2QAAAAAAAAAAQAAAK1hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAEAAQABIAAAASAAAAAAA" +
  "AAABFExhdmM2My4xLjEwMiBsaWJ4MjY0AAAAAAAAAAAAAAAAGP//AAAAM2F2Y0MBZAAK/+EAF2dkAAqstCE2AiAAAAMAIAAA" +
  "AwKB4kTUAQAFaO8DnLD9+PgAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAARuIAAAAAAAAAGHN0dHMAAAAAAAAAAQAA" +
  "AAYAAAQAAAAAGHN0c3MAAAAAAAAAAgAAAAEAAAAEAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAGAAAAAQAAACxzdHN6AAAAAAAA" +
  "AAAAAAAGAAADqQAAABEAAAAWAAABXwAAABAAAAASAAAAFHN0Y28AAAAAAAAAAQAAA3MAAABhdWR0YQAAAFltZXRhAAAAAAAA" +
  "ACFoZGxyAAAAAAAAAABtZGlyYXBwbAAAAAAAAAAAAAAAACxpbHN0AAAAJKl0b28AAAAcZGF0YQAAAAEAAAAATGF2ZjYzLjEu" +
  "MTAyAAAACGZyZWUAAAVZbWRhdAAAAmsGBf//Z9xF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjUgcjMyMjIgYjM1NjA1" +
  "YSAtIEguMjY0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjUgLSBodHRwOi8vd3d3LnZpZGVvbGFuLm9y" +
  "Zy94MjY0Lmh0bWwgLSBvcHRpb25zOiBjYWJhYz0xIHJlZj0xIGRlYmxvY2s9MTowOjAgYW5hbHlzZT0weDM6MHgxMTMgbWU9" +
  "aGV4IHN1Ym1lPTIgcHN5PTEgcHN5X3JkPTEuMDA6MC4wMCBtaXhlZF9yZWY9MCBtZV9yYW5nZT0xNiBjaHJvbWFfbWU9MSB0" +
  "cmVsbGlzPTAgOHg4ZGN0PTEgY3FtPTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9xcF9vZmZzZXQ9MCB0" +
  "aHJlYWRzPTIgbG9va2FoZWFkX3RocmVhZHM9MSBzbGljZWRfdGhyZWFkcz0wIG5yPTAgZGVjaW1hdGU9MSBpbnRlcmxhY2Vk" +
  "PTAgYmx1cmF5X2NvbXBhdD0wIGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1lcz0wIHdlaWdodHA9MSBrZXlpbnQ9MyBrZXlp" +
  "bnRfbWluPTIgc2NlbmVjdXQ9MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTMgcmM9Y3JmIG1idHJlZT0xIGNyZj00" +
  "MC4wIHFjb21wPTAuNjAgcXBtaW49MCBxcG1heD02OSBxcHN0ZXA9NCBpcF9yYXRpbz0xLjQwIGFxPTE6MS4wMACAAAABNmWI" +
  "hBX/0NsosypPpt2SC+9hYgczgoKR/E/jIvTaIDfTqx82w8n1S+2mXaRnolnspFDKl+77RJbGR+ffyvzM2HV8MwPgu3fT+jJM" +
  "wLWYANg6gwqOTwM1Ji1B/J3C54TjPk6Jv2lv0kDtTtSvJhJDtqCmet7sMsej3+bshvsb3hjT2pvvuV4jnoVdsEfpXwd4f4oc" +
  "E+ZoavTCDDok8Da6gUWE2FJo7HLKzMY+LLmAR3hj/4dHKyEJEu4BlCdKaWbWprPC7lc32hGXGELI2YxhwwaY3GpKX+bgUNlG" +
  "2UySZDT//kh2PmWvahR8Jz/SiJNp6OkqCzmEx7ZCrly+QL7VumYz2ZMvny4cPPSERPnrLKWLDnHNMB6S8tzRHTsr4BAtarUK" +
  "jmYKT/quQF6CPOnp2v+6dzWhPjkAAAANQZomIr9gPhebWrl/qAAAABJBmkYiv2LinhYcxUU/eq4rAJEAAAFbZYiCDf/T4fhH" +
  "A7+30RMqcbm4ApBTqRgEI2B9fXlaoda3sM+19ePr4vmSD4ct+tnN3UZTGx1xq9RqiftJE0f95H+7ehB6we+9wrL9YWbOFIwU" +
  "HT1VfN03LRQj5hq/u3hPzrtygsX6MREdDe+Nkwn06MbwFGn8iGvrP98aBBYZYIyxZ287zB+8FR6OcI8ggmd9+2p5PVe4RXOu" +
  "kQ7/3MwO/i2CyZf0oVHCp6K1b5qxAGI85Bq1llWgF+n5DB9oAi00Nxj7Dw5Rt4iSyKsx8kHCzX8T74iVUYmqnAMAdmHNLbWr" +
  "DHj8I3fBpKSYh2drAIBTm3L2ec1eIHi+JW/32sl1zQaP+LdnOeozV/5uuoKEWQuVW2Jl/Cz3T9ojUd61ReLMJQaU064kXuHu" +
  "UfMaa6zwKAYQqOJQHkJkCSsvDjLakwnlLIOuBDwyUyY5akayM+MaC34NLQ+5UdO4OKoAAAAMQZomI79vMJ/TdOwnAAAADkGa" +
  "RiEvfQpQajZjPpc/",
);

function base64Bytes(text: string): Uint8Array {
  const binary = atob(text);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}
